# Generated by Django 5.0.6 on 2024-05-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1-ви клас'), (2, '2-ви клас'), (3, '3-ти клас'), (4, '4-ти клас'), (5, '5-ти клас'), (6, '6-ти клас'), (7, '7-ми клас'), (8, '8-ми клас'), (9, '9-ти клас'), (10, '10-ти клас'), (11, '11-ти клас'), (12, '12-ти клас')], null=True),
        ),
    ]
